/Users/ishaan/miniconda3/envs/nicewebrl/lib/python3.10/site-packages/flashbax/buffers/trajectory_buffer.py:473: UserWarning: Setting max_size dynamically sets the `max_length_time_axis` to be `max_size`//`add_batch_size = 1000`.This allows one to control exactly how many timesteps are stored in the buffer.Note that this overrides the `max_length_time_axis` argument.
  warnings.warn(
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ishaan/CS/Research/CarvalhoRL/twosteptask/dqnNew.py", line 295, in <module>
    main()
  File "/Users/ishaan/CS/Research/CarvalhoRL/twosteptask/dqnNew.py", line 292, in main
    outs = jax.block_until_ready(train_vjit(rngs))
  File "/Users/ishaan/CS/Research/CarvalhoRL/twosteptask/dqnNew.py", line 87, in train
    _action = basic_env.action_space().sample(rng)
NameError: name 'basic_env' is not defined
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ishaan/CS/Research/CarvalhoRL/twosteptask/dqnNew.py", line 295, in <module>
    main()
  File "/Users/ishaan/CS/Research/CarvalhoRL/twosteptask/dqnNew.py", line 292, in main
    outs = jax.block_until_ready(train_vjit(rngs))
  File "/Users/ishaan/CS/Research/CarvalhoRL/twosteptask/dqnNew.py", line 87, in train
    _action = basic_env.action_space().sample(rng)
NameError: name 'basic_env' is not defined
